module "ai" {
  source                             = "git::https://github.com/hmcts/terraform-module-ai-services?ref=main"
  env                                = var.env
  project                            = var.project
  existing_resource_group_name       = azurerm_resource_group.rg.name
  common_tags                        = module.common_tags.common_tags
  product                            = var.product
  component                          = var.component
  files_storage_account_id           = data.azurerm_storage_account.ingest_storage_account.id
  key_vault_id                       = module.key_vault.key_vault_id
  application_insights_id            = module.application_insights.id
  create_ml_workspace                = true
  create_cognitive_account           = true
  cognitive_account_kind             = "FormRecognizer"
  cognitive_account_sku              = var.cognitive_account_sku
  existing_cognitive_account_name    = var.existing_cognitive_account_name
  subnet_id                          = data.azurerm_subnet.private_endpoint_subnet.id
  min_node_count                     = var.min_node_count
  ip_rules                           = var.cognitive_account_ip_rules
  instances                          = var.ml_compute_instances
  compute_instance_public_ip_enabled = var.compute_instance_public_ip_enabled
}
